// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_row", "crow2");
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_us", "cus2");
user_pref("app.normandy.startupExperimentPrefs.privacy.annotate_channels.strict_list.enabled", false);
user_pref("app.normandy.startupExperimentPrefs.urlclassifier.trackingAnnotationTable.testEntries", "etp-experiment-2.dummytracker.org");
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.isCollectionDismissible", true);
user_pref("app.normandy.user_id", "3dc48310-df5b-4551-a693-06e79a7ac2ef");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1591556211);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1591556188);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1591556185);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1591556241);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 8669);
user_pref("browser.cache.disk.capacity", 962560);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1591556181);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0f1587d2-b70c-45f5-b310-867b7f201108}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1591556251580");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1591558076580");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1591556192918");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1591559792918");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.region", "GB");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 2915);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1591556184);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1591556185588");
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "cc37c4e753cf405c957afbaed0e9b2fc");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"6f4baa58-744d-430f-9fea-58bb3da1cd72\",\"formautofill@mozilla.org\":\"a3729e20-18c3-460b-ba90-1c04590bfc71\",\"screenshots@mozilla.org\":\"9ed0334b-8c25-4eae-bfa3-794898a37b0f\",\"webcompat-reporter@mozilla.org\":\"180290d3-73ae-4b30-a6fe-acc7e1dd07db\",\"webcompat@mozilla.org\":\"60c4d1e1-9c17-496c-a2e0-ed3926fbff45\",\"default-theme@mozilla.org\":\"17c65829-f25b-492d-aaac-873833efcb23\",\"google@search.mozilla.org\":\"d770f9c3-3ed5-4c15-803f-8630149c3098\",\"amazondotcom@search.mozilla.org\":\"ee24b071-b8d7-4187-810a-0114f6bbb6b0\",\"bing@search.mozilla.org\":\"3894a16c-7afa-4ffc-86db-39e804272856\",\"ddg@search.mozilla.org\":\"e065d05c-22bd-4beb-99bc-cfcc7a94bff1\",\"ebay@search.mozilla.org\":\"dbc8a968-d0ff-4f31-b62e-0a2d3539c159\",\"twitter@search.mozilla.org\":\"9f797943-cf6b-44d7-a59c-0e93958bde41\",\"wikipedia@search.mozilla.org\":\"532e63e7-a3c4-4416-b2ee-167af5e1383f\",\"amazon@search.mozilla.org\":\"07478d49-fb7c-4670-a57d-41f3e51a2943\"}");
user_pref("gfx-shader-check.build-version", "20200602222727");
user_pref("gfx-shader-check.device-id", "0x3ea0");
user_pref("gfx-shader-check.driver-version", "25.20.100.6577");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "77.0.1");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x3ea0");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "25.20.100.6577");
user_pref("layers.mlgpu.sanity-test-failed", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x3ea0");
user_pref("sanity-test.driver-version", "25.20.100.6577");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200602222727");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{82b8aa47-2f3b-4142-8c84-7845f0be2354}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{41281caf-2728-468c-bdbe-3632c1d06245}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1591556180);
user_pref("toolkit.telemetry.cachedClientID", "28f954f2-43c0-4c9d-b42e-904cdfbe1455");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
